---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/equipment
  label: Utstyr
  create: documents
  match: "*"
  templates:
  - equipment
- type: directory
  path: content/frontpages
  label: Forsideoppslag
  create: all
  match: "/*"
- type: directory
  path: content/galleries
  label: Gallerier
  create: documents
  match: "*"
  new_doc_ext: md
  templates:
  - gallery
  - 360gallery
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.2
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.2
